#!/usr/bin/env php
<?php

namespace JLaso\HideMessage;

require_once __DIR__ . '/../vendor/autoload.php';

use JLaso\HideMessage\Command\DecodeCommand;
use JLaso\HideMessage\Command\EncodeCommand;
use JLaso\HideMessage\Command\TransCommand;
use Symfony\Component\Console\Application;

$application = new Application();
$application->addCommands(
    array(
        new EncodeCommand(),
        new DecodeCommand(),
        new TransCommand(),
    )
);
$application->run();
